### ISSUE TITLE
Native Instruments Komplete Control S25 & Bitwig

### ISSUE THREAD

**Issue by LewisSC** [git-moss/DrivenByMoss-Documentation#26]
Hello.  I've encountered an issue when trying to assign the Midi Port and USB Port in Bitwig.  I'm running KXStudio on Ubuntu Mate 20.04 LTS with the latest version of Bitwig.  The S25 is recognized by the OS and Catia and I am able to use the Bitwig provided S25 driver with some success (note input and encoder response is appropriate.  Pitch, mod and octave buttons work).  However, my intent was to use the Driven by Moss extensions for this unit.  When I try to assign Midi and USB ports to take advantage of the Driven by Moss extension, Bitwig audio engine crashes every time the controller tries to enable upon port selection.  I've tried numerous different USB cables and ports with the same results.

Regards,
Scott.

**Comment by git-moss** [comment]
Thanks for reporting, I can reproduce the issue.

The problem is that you need to give your user access to the USB port. I updated the necessary file with the data for the Kontrol MkI devices: https://github.com/git-moss/DrivenByMoss/blob/master/resources/99-userusbdevices.rules
See the Ableton Push Installation notes in the manual about where to copy this (will update the manual later).

However, it is still not working for me: the extension starts up fine but there is no update on the device (besides the keyboard working). I tried to run it as root and this works fine. So, I am running out of ideas here. Maybe you have an idea?

BTW, please report issues here: https://github.com/git-moss/DrivenByMoss/issues

**Comment by LewisSC** [comment]
Thank you for the reply.  Adding the rules corrected the issue I reported.  The extension loads successfully when MIDI and USB ports are assigned.  I note the same outcome as you concerning the device update, however.  The device is not updated successfully with the scripted features.  Assigning "root" membership to my user account doesn't seem to change that in my case either.  The extension diagnostics in Bitwig reports that USB HID Device is inaccessible.

**Comment by git-moss** [comment]
I meant to start Bitwig as root with "sudo". But it will then run in the root environment without any settings or registration but you can also start as demo for testing.

**Comment by LewisSC** [comment]
Thanks, for the clarification.  I just tried that and observed the same outcome as you (i.e. proper function).  It seems clear there is likely a limitation imposed by the privileges extended by the audio group in my configuration.  I'll investigate that angle some more.  Apologies for opening the issue in the incorrect place.  More important, thank you very much for your expertise and work on the extension.  I use Generic Flexi and the Novation Launchpad Pro features routinely and the benefits have been substantial!

**Comment by LewisSC** [comment]
It appears that I fixed this by modifying the relevant udev rule to the plural expression (i.e. "SUBSYSTEMS" and "ATTRS" to assign privileges for both the subordinate device and the parent device.  

SUBSYSTEMS=="usb",ATTRS{idVendor}=="17cc",ATTRS{idProduct}=="1340",MODE="0660",GROUP="audio"

**Comment by git-moss** [comment]
Many thanks! Just tried it and it works fine for me, too! Will update the file in the next update.
